# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/
global_vars:
  - name: "today"
    type: "date"
    params:
      format: "%Y.%m.%d"

  - name: "zkid"
    type: "date"
    params:
      format: "%Y%m%d%H%M"

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Dates
  - trigger: ":td"
    replace: "{{today}}"

  - trigger: ":ytd"
    replace: "{{yesterday}}"
    vars:
      - name: yesterday
        type: shell
        params:
          cmd: "bash -c 'date +%Y.%m.%d -d -1day'"

  - trigger: ":zk"
    replace: "{{zkid}}"

  # Why not?
  - trigger: ":flip"
    replace: "`(╯°□°）╯︵ ┻━┻`"

  - trigger: ":sh"
    replace: "`¯\\_(ツ)_/¯`"
